/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;


import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

public class AppTest {
    @Test
    public void appHasAGreeting() {
        App classUnderTest = new App();
        Assertions.assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
